regex1 = r"....."
regex2 = r" [a-zA-Zа-яА-ЯёЁ][a-zA-Zа-яА-ЯёЁ][a-zA-Zа-яА-ЯёЁ] "
regex3 = r"\b[a-zA-Zа-яА-ЯёЁ][a-zA-Zа-яА-ЯёЁ][a-zA-Zа-яА-ЯёЁ]\b"
regex4 = r"^[a-zA-Zа-яА-ЯёЁ][a-zA-Zа-яА-ЯёЁ][a-zA-Zа-яА-ЯёЁ][a-zA-Zа-яА-ЯёЁ]\b"
regex5 = r"\.\.\."
